/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = string;
export type Source = "claude_code" | "openai_agents" | "langgraph" | "crewai" | "autogen" | "custom";
export type ExternalId = string;
export type Title = string | null;
export type StartedAt = string | null;
export type EndedAt = string | null;
export type Status = string;
export type ExternalId1 = string;
export type Name = string;
export type Role = string | null;
export type Model = string | null;
export type Agents = AgentInfo[];
export type ExternalId2 = string;
export type Name1 = string;
export type Transport = string | null;
export type Url = string | null;
export type Tools = string[];
export type McpServers = McpServerInfo[];
export type ExternalSpanId = string;
export type ParentExternalSpanId = string | null;
export type SpanKind =
  | "session_root"
  | "agent"
  | "llm"
  | "tool"
  | "mcp_tool"
  | "file_io"
  | "memory"
  | "handoff"
  | "chain"
  | "retrieval"
  | "custom";
export type Name2 = string;
export type AgentExternalId = string | null;
export type McpServerExternalId = string | null;
export type Status1 = string;
export type StartTime = string | null;
export type EndTime = string | null;
export type IOType =
  | "prompt"
  | "response"
  | "tool_input"
  | "tool_output"
  | "file_read"
  | "file_write"
  | "memory_read"
  | "memory_write";
export type Role1 = string | null;
export type ContentText = string | null;
export type FilePath = string | null;
export type ByteSize = number | null;
export type Io = IORecord[];
export type Model1 = string | null;
export type InputTokens = number;
export type OutputTokens = number;
export type CacheReadTokens = number;
export type CacheWriteTokens = number;
export type CostUsd = number | null;
export type ErrorType = string | null;
export type Message = string | null;
export type Stack = string | null;
export type Spans = SpanInput[];
export type SourceExternalSpanId = string;
export type TargetExternalSpanId = string;
export type EdgeKind = "call" | "handoff" | "data_flow" | "mcp_link" | "file_dep" | "memory_dep";
export type Label = string | null;
export type Edges = EdgeInput[];

/**
 * A complete (or appended) trace, normalized across frameworks.
 */
export interface CanonicalEnvelope {
  schema_version?: SchemaVersion;
  source: Source;
  session: SessionInfo;
  agents?: Agents;
  mcp_servers?: McpServers;
  spans?: Spans;
  edges?: Edges;
}
export interface SessionInfo {
  external_id: ExternalId;
  title?: Title;
  started_at?: StartedAt;
  ended_at?: EndedAt;
  status?: Status;
  meta?: Meta;
}
export interface Meta {
  [k: string]: unknown;
}
export interface AgentInfo {
  external_id: ExternalId1;
  name: Name;
  role?: Role;
  model?: Model;
  meta?: Meta1;
}
export interface Meta1 {
  [k: string]: unknown;
}
export interface McpServerInfo {
  external_id: ExternalId2;
  name: Name1;
  transport?: Transport;
  url?: Url;
  tools?: Tools;
  meta?: Meta2;
}
export interface Meta2 {
  [k: string]: unknown;
}
export interface SpanInput {
  external_span_id: ExternalSpanId;
  parent_external_span_id?: ParentExternalSpanId;
  kind: SpanKind;
  name: Name2;
  agent_external_id?: AgentExternalId;
  mcp_server_external_id?: McpServerExternalId;
  status?: Status1;
  start_time?: StartTime;
  end_time?: EndTime;
  attributes?: Attributes;
  io?: Io;
  cost?: CostRecord | null;
  error?: ErrorInfo | null;
}
export interface Attributes {
  [k: string]: unknown;
}
export interface IORecord {
  io_type: IOType;
  role?: Role1;
  content_text?: ContentText;
  file_path?: FilePath;
  byte_size?: ByteSize;
  meta?: Meta3;
}
export interface Meta3 {
  [k: string]: unknown;
}
export interface CostRecord {
  model?: Model1;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  cache_read_tokens?: CacheReadTokens;
  cache_write_tokens?: CacheWriteTokens;
  cost_usd?: CostUsd;
}
export interface ErrorInfo {
  error_type?: ErrorType;
  message?: Message;
  stack?: Stack;
  meta?: Meta4;
}
export interface Meta4 {
  [k: string]: unknown;
}
export interface EdgeInput {
  source_external_span_id: SourceExternalSpanId;
  target_external_span_id: TargetExternalSpanId;
  kind?: EdgeKind;
  label?: Label;
  meta?: Meta5;
}
export interface Meta5 {
  [k: string]: unknown;
}
