"""baseline schema

Revision ID: 2764d4ca9614
Revises: 
Create Date: 2026-06-07 06:57:28.808065
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2764d4ca9614'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_price',
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('input_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_read_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_write_per_mtok', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('model')
    )
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_session_source_external')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_source'), ['source'], unique=False)
        batch_op.create_index('ix_session_started_at', ['started_at'], unique=False)

    op.create_table('agent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'name', name='uq_agent_session_name')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_session_id'), ['session_id'], unique=False)

    op.create_table('mcp_server',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'name', name='uq_mcp_session_name')
    )
    with op.batch_alter_table('mcp_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_session_id'), ['session_id'], unique=False)

    op.create_table('raw_trace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('span',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('external_span_id', sa.String(length=255), nullable=False),
    sa.Column('parent_span_id', sa.Uuid(), nullable=True),
    sa.Column('span_kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('mcp_server_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_server.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_span_id'], ['span.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'external_span_id', name='uq_span_session_external')
    )
    with op.batch_alter_table('span', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_span_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_span_parent_span_id'), ['parent_span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_span_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_span_session_kind', ['session_id', 'span_kind'], unique=False)
        batch_op.create_index('ix_span_session_sequence', ['session_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_span_span_kind'), ['span_kind'], unique=False)

    op.create_table('cost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['span.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_span_id'), ['span_id'], unique=False)

    op.create_table('edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('source_span_id', sa.Uuid(), nullable=False),
    sa.Column('target_span_id', sa.Uuid(), nullable=False),
    sa.Column('edge_kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_span_id'], ['span.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_span_id'], ['span.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edge_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_edge_session_kind', ['session_id', 'edge_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_edge_source_span_id'), ['source_span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edge_target_span_id'), ['target_span_id'], unique=False)

    op.create_table('error',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['span.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_span_id'), ['span_id'], unique=False)

    op.create_table('span_io',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('span_id', sa.Uuid(), nullable=False),
    sa.Column('io_type', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_ref', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['span_id'], ['span.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('span_io', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_span_io_file_path'), ['file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_span_io_span_id'), ['span_id'], unique=False)
        batch_op.create_index('ix_span_io_span_type', ['span_id', 'io_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('span_io', schema=None) as batch_op:
        batch_op.drop_index('ix_span_io_span_type')
        batch_op.drop_index(batch_op.f('ix_span_io_span_id'))
        batch_op.drop_index(batch_op.f('ix_span_io_file_path'))

    op.drop_table('span_io')
    with op.batch_alter_table('error', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_span_id'))
        batch_op.drop_index(batch_op.f('ix_error_session_id'))

    op.drop_table('error')
    with op.batch_alter_table('edge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edge_target_span_id'))
        batch_op.drop_index(batch_op.f('ix_edge_source_span_id'))
        batch_op.drop_index('ix_edge_session_kind')
        batch_op.drop_index(batch_op.f('ix_edge_session_id'))

    op.drop_table('edge')
    with op.batch_alter_table('cost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_span_id'))
        batch_op.drop_index(batch_op.f('ix_cost_session_id'))
        batch_op.drop_index(batch_op.f('ix_cost_model'))
        batch_op.drop_index(batch_op.f('ix_cost_agent_id'))

    op.drop_table('cost')
    with op.batch_alter_table('span', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_span_span_kind'))
        batch_op.drop_index('ix_span_session_sequence')
        batch_op.drop_index('ix_span_session_kind')
        batch_op.drop_index(batch_op.f('ix_span_session_id'))
        batch_op.drop_index(batch_op.f('ix_span_parent_span_id'))
        batch_op.drop_index(batch_op.f('ix_span_agent_id'))

    op.drop_table('span')
    op.drop_table('raw_trace')
    with op.batch_alter_table('mcp_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_session_id'))

    op.drop_table('mcp_server')
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_session_id'))

    op.drop_table('agent')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index('ix_session_started_at')
        batch_op.drop_index(batch_op.f('ix_session_source'))
        batch_op.drop_index(batch_op.f('ix_session_external_id'))

    op.drop_table('session')
    op.drop_table('model_price')
    # ### end Alembic commands ###
